services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5353:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


# run using:
# docker-compose up -d

# stop using:
# docker-compose down

# to connect to the database, use:
# docker exec -it my_postgres psql -U myuser -d mydb

